apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: team2-api
  namespace: team2-demo
  labels:
    app: gateway-team2
    component: api-proxy
spec:
  path: /api
  to:
    kind: Service
    name: gateway-team2
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
