apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: team2-backend
  namespace: team2-demo
  labels:
    app: backend-team2
    component: api
spec:
  path: /api
  to:
    kind: Service
    name: backend-team2
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
