apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team2-demo

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - gateway-deployment.yaml

commonLabels:
  app.kubernetes.io/name: team2-demo
