apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: team2-demo

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - gateway-deployment.yaml
  - route.yaml
  - network-policy.yaml

images:
  - name: ${REGISTRY}/team2-backend
    newTag: ${VERSION}
  - name: ${REGISTRY}/team2-gateway
    newTag: ${VERSION}

commonLabels:
  app.kubernetes.io/name: team2-demo
  app.kubernetes.io/part-of: team2-demo
